# Generated by Django 5.2 on 2025-04-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_reward_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
